name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Clean Gradle cache
        run: ./gradlew clean

      - name: Build and test with Gradle
        run: ./gradlew build

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/libs/*.jar
