name: Java CI with Gradle  

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      
    - name: Clean Gradle cache
      run: ./gradlew clean
      

      
    - name: Test with Gradle
      run: ./gradlew test
      env:
        CLASSPATH: ./src/test/java


      
    - name: Build project
      run: ./gradlew assemble -Dorg.gradle.project.snapshot=true        

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build/libs/*.jar
        
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports/tests/test/
  
    - name: Download Test Results
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: test-results
    
    - name: Publish Test Results as Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./test-results/
